services:
  caldera:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        NEXT_PUBLIC_BASALT_WS_URL: wss://testnet.basalt.foundation
        NEXT_PUBLIC_BASALT_API_URL: http://rpc-0:5000
    container_name: basalt-caldera
    networks:
      - basalt-testnet
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

networks:
  basalt-testnet:
    external: true
